### ISSUE TITLE
ID/UUID in Yaml files

### ISSUE THREAD

**Issue by adulau** [splunk/attack_data#448]
Hi Folks,

We would like to integrate your ATT&CK data in [CyCAT.org](https://www.cycat.org) which is another open source project.  But we have seen that a lot of yaml files don't include an ID/UUID? Do you plan to add one? It would help a lot to uniquely identify the rule.

Thanks a lot.

Cheers

**Comment by d1vious** [comment]
@adulau this is a great suggestion and easy enough to implement, we will include them in our yaml.

**Comment by d1vious** [comment]
Added the UUIDs to all data sets and updated our docs to make sure it is included as part of the structure.

**Comment by adulau** [comment]
Thank you very much! I will add the data in CyCAT in the next days.
