### ISSUE TITLE
python bin/replay.py -c bin/replay.yml   File "bin/replay.py", line 55     print (line.replace(original_time, new_time),end ='') ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by anilreddydonthireddy** [splunk/attack_data#690]
Hi, 

When I trying to run replay.py I am getting below error that syntax is invalid. 

python bin/replay.py -c bin/replay.yml
  File "bin/replay.py", line 55
    print (line.replace(original_time, new_time),end ='')
                                                     ^
SyntaxError: invalid syntax

Please help me to resolve the issue.

Thanks.

**Comment by d1vious** [comment]
hey I believe this was fixed @anilreddydonthireddy, thank you for raising it!
