### ISSUE TITLE
cant clone

### ISSUE THREAD

**Issue by Ondjultomte** [splunk/attack_data#870]
git@splunk:/tmp$ git clone git@github.com:splunk/attack_data.git
Cloning into 'attack_data'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by pyth0n1c** [comment]
Hi @Ondjultomte !
Can you please try cloning the repo with the following instead:
`git clone https://github.com/splunk/attack_data`

Thank you!
